volumes:
  DB_DATA:

services:
  db:
    image: "postgres:15-alpine"
    restart: "no"
    ports:
      - "5314:5432"
    environment:
      POSTGRES_USER: spotify_gin
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: spotify_gin
      PGDATA: /db_data
    volumes:
      - DB_DATA:/db_data

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6378:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  swagger:
    image: ghcr.io/swaggo/swag:latest
    volumes:
      - ./src:/code
    entrypoint: swag init
